About
Damian-Bukowski/wypozyczalnia-kostiumow-adk pull request #3
Opened 2020-06-07 11:54 UTC by Damian-Bukowski

2020-06-07 11:55 UTC, Joanna-Adamczyk commented on src/main/java/com/sda/controller/CostumeController.java
> +
zbedna linia

2020-06-07 13:34 UTC, Joanna-Adamczyk approved these changes

2020-06-07 13:35 UTC, krzysztofic approved these changes

2020-06-20 07:17 UTC, nowszy94 requested changes

2020-06-20 07:17 UTC, nowszy94 commented on src/main/java/com/sda/controller/CostumeController.java
> +    public String About() {
about z malej litery

2020-06-20 07:17 UTC, nowszy94 commented on src/main/resources/application.properties
> +server.port = 8081
wyrzucmy ta linie

2020-06-20 07:23 UTC, Damian-Bukowski commented on src/main/java/com/sda/controller/CostumeController.java
> +    public String About() {
Resolved.

2020-06-20 07:23 UTC, Damian-Bukowski commented on src/main/resources/application.properties
> +server.port = 8081
Resolved.

2020-06-20 07:33 UTC, nowszy94 approved these changes

2020-06-20 07:54 UTC, merged