Costume searchbar
Damian-Bukowski/wypozyczalnia-kostiumow-adk pull request #7
Opened 2020-06-19 15:53 UTC by Damian-Bukowski

2020-06-20 07:26 UTC, nowszy94 requested changes

2020-06-20 07:26 UTC, nowszy94 commented on src/main/java/com/sda/controller/CostumeController.java
> +    /*@GetMapping("/costumes/{name}")
komentarz 😱

2020-06-20 07:26 UTC, nowszy94 commented on src/main/java/com/sda/controller/CostumeController.java
> +    public ModelAndView showAll(Model model, @RequestParam(defaultValue="") String name) {
Myślę że lepiej byłoby rozbić to na dwie różne metody, w jednej w którym query parametr name jest required (showByName) oraz drugi bez wskazania query parametrów (showAll)

2020-06-20 07:26 UTC, nowszy94 commented on src/main/java/com/sda/service/OrderService.java
> +        return costumeRepository.findByNameLike("%"+name+"%");
czy te procenty są potrzebne?

2020-06-20 07:29 UTC, Damian-Bukowski commented on src/main/java/com/sda/controller/CostumeController.java
> +    /*@GetMapping("/costumes/{name}")
resolved

2020-06-20 07:33 UTC, Damian-Bukowski commented on src/main/java/com/sda/service/OrderService.java
> +        return costumeRepository.findByNameLike("%"+name+"%");
Faktycznie przy tym projekcie funkcja zbedna. Deleted.

2020-06-20 12:45 UTC, Damian-Bukowski commented on src/main/java/com/sda/service/OrderService.java
> +        return costumeRepository.findByNameLike("%"+name+"%");
resolved.

2020-06-20 12:46 UTC, Joanna-Adamczyk approved these changes

2020-06-21 00:25 UTC, nowszy94 approved these changes

2020-06-21 09:34 UTC, krzysztofic approved these changes

2020-07-25 11:10 UTC, merged